# Generated by Django 2.2.5 on 2020-01-13 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Edad', models.IntegerField()),
                ('Nacionalidad', models.CharField(max_length=100)),
                ('FechaDeNacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Canciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('FechaLanzamiento', models.DateField()),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canciones.Autores')),
            ],
        ),
    ]
